// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rrQ8TsO0_fjFa9b4iLDUFc55N5DA4Fg',
    appId: '1:1070829614731:web:7d7c5f472646e09a7ac68e',
    messagingSenderId: '1070829614731',
    projectId: 'voyage-cab-booking',
    authDomain: 'voyage-cab-booking.firebaseapp.com',
    databaseURL: 'https://voyage-cab-booking-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-cab-booking.appspot.com',
    measurementId: 'G-BVWY38J3LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSQThMVjjBFZfH6KExilsDSF1oUcuFQsI',
    appId: '1:1070829614731:android:6d394cc43507a33c7ac68e',
    messagingSenderId: '1070829614731',
    projectId: 'voyage-cab-booking',
    databaseURL: 'https://voyage-cab-booking-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-cab-booking.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChQLBB0WUuSWLJ0iGm1Qy0Awkx4PvY2HI',
    appId: '1:1070829614731:ios:ad82e20d419831157ac68e',
    messagingSenderId: '1070829614731',
    projectId: 'voyage-cab-booking',
    databaseURL: 'https://voyage-cab-booking-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-cab-booking.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChQLBB0WUuSWLJ0iGm1Qy0Awkx4PvY2HI',
    appId: '1:1070829614731:ios:ad82e20d419831157ac68e',
    messagingSenderId: '1070829614731',
    projectId: 'voyage-cab-booking',
    databaseURL: 'https://voyage-cab-booking-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-cab-booking.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6rrQ8TsO0_fjFa9b4iLDUFc55N5DA4Fg',
    appId: '1:1070829614731:web:95b0bc7de74927c97ac68e',
    messagingSenderId: '1070829614731',
    projectId: 'voyage-cab-booking',
    authDomain: 'voyage-cab-booking.firebaseapp.com',
    databaseURL: 'https://voyage-cab-booking-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-cab-booking.appspot.com',
    measurementId: 'G-P306WZ8DY9',
  );

}